# Site settings
title: Cisco Developer Challenge
email: devx@cisco.com
description: "Welcome to the Cisco Developer Challenge Series powered by [topcoder]! Are you ready to compete and earn rewards for your code or creativity?"
baseurl: ""
url: "http://www.topcoder.com/cisco"

# Build settings
markdown: kramdown
permalink: pretty
